apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: nginx-tls-certificate-secret
  issuerRef:
    kind: ClusterIssuer
    name: {{ required "Cluster issuer name is required" .Values.clusterIssuer.name }}
  dnsNames: 
    - {{ required "Hostname is not defined" .Values.hostname }}