apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-map
  namespace: {{ .Release.Namespace }}
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body>
        <h1>Hello World!</h1>
        <p>This is a sample HTML page served by NGINX.</p>
    </body>
    </html>
