apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ required "Hostname is not defined" .Values.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: 
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.service.port }}
  tls:
    - secretName: nginx-tls-certificate-secret
      hosts: 
        - {{ required "Hostname is not defined" .Values.hostname }}