- name: Ensure lxc config has the right apparmor profile
  ansible.builtin.lineinfile:
    dest: "/etc/pve/lxc/{{ item }}.conf"
    regexp: ^lxc.apparmor.profile
    line: "lxc.apparmor.profile: unconfined"
  loop: "{{ proxmox_lxc_container_vmids }}"
  notify: reboot containers

- name: Ensure lxc config has the right cgroup
  ansible.builtin.lineinfile:
    dest: "/etc/pve/lxc/{{ item }}.conf"
    regexp: ^lxc.cgroup.devices.allow
    line: "lxc.cgroup.devices.allow: a"
  loop: "{{ proxmox_lxc_container_vmids }}"
  notify: reboot containers

- name: Ensure lxc config has the right cap drop
  ansible.builtin.lineinfile:
    dest: "/etc/pve/lxc/{{ item }}.conf"
    regexp: ^lxc.cap.drop
    line: "lxc.cap.drop: "
  loop: "{{ proxmox_lxc_container_vmids }}"
  notify: reboot containers

- name: Ensure lxc config has the right mounts
  ansible.builtin.lineinfile:
    dest: "/etc/pve/lxc/{{ item }}.conf"
    regexp: ^lxc.mount.auto
    line: 'lxc.mount.auto: "proc:rw sys:rw"'
  loop: "{{ proxmox_lxc_container_vmids }}"
  notify: reboot containers
