include:
  - ./nginx/docker-compose.yml
  - ./cloudflare-ddns/docker-compose.yml
  - ./jellyfin/docker-compose.yml
  - ./immich/docker-compose.yml
  - ./paperless/docker-compose.yml
  - ./ofelia/docker-compose.yml
  - ./authelia/docker-compose.yml
  - ./tandoor/docker-compose.yml
  - ./bind9/docker-compose.yml
  - ./brewapi/docker-compose.yml
