services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./homepage:/app/config
    env_file: .env
    environment:
      PUID: 1000
      PGID: 1000

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    env_file: .env
    environment:
      DB_MYSQL_HOST: nginx-db 
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: nginx
      DB_MYSQL_NAME: nginx
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - nginx-data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - nginx-db

  nginx-db:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: nginx
      MYSQL_USER: nginx
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - nginx-db-data:/var/lib/mysql
    
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - ./jellyfin:/config
      - jellyfin-cache:/cache
      - /home/vjrasane/shared/media:/media
    restart: always
    environment:
      - JELLYFIN_PublishedServerUrl=http://rpi5-01:8096
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8096:8096

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - syncthing-data:/config
      - /home/vjrasane/shared:/shared
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: always 

volumes:
  nginx-data:
    driver: local
  nginx-db-data: 
    driver: local
  portainer_data:
    driver: local
  jellyfin-cache:
    driver: local
  syncthing-data:
    driver: local
