version: '3'
includes:
  tf:
    taskfile: ./terraform/Taskfile.yaml
    dir: ./terraform
  helm:
    taskfile: ./helm/Taskfile.yaml
    dir: ./helm

tasks:
  default:
    silent: true
    cmds:
      - task -l

  hide:
    cmds:
      - git secret hide -m -P

  reveal:
    cmds:
      - git secret reveal -f -P
