---
- name: Install packages
  ansible.builtin.package:
    name:
      - curl
    state: present
    update_cache: true

- name: Create conf-kmsg.sh file
  ansible.builtin.template:
    src: conf-kmsg.sh.j2
    dest: /usr/local/bin/conf-kmsg.sh
    owner: root
    group: root
    mode: "0755"
  notify: reboot server

- name: Create service conf
  ansible.builtin.template:
    src: conf-kmsg.service.j2
    dest: /etc/systemd/system/conf-kmsg.service
    owner: root
    group: root
    mode: '0755'

- name: Enable conf-kmsg service
  ansible.builtin.service:
    name: conf-kmsg
    enabled: true
    state: started
