---
- name: Wait for hosts to be reachable
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Wait for SSH
      ansible.builtin.wait_for_connection:

- name: Configure LXC containers
  hosts: all
  tasks:
    - name: Ping the host
      ansible.builtin.ping:

    - name: Set timzone
      community.general.timezone:
        name: "{{ system_timezone | default('Europe/Helsinki') }}"
      notify: reboot server

    - name: Install packages
      ansible.builtin.package:
        name:
          - curl
          - jq
        state: present
        update_cache: true

    - name: Enable IPv4 forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: true
      notify: reboot server

    - name: Enable IPv6 forwarding
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.forwarding
        value: "1"
        state: present
        reload: true
      notify: reboot server

    - name: Enable IPv6 router advertisements
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.accept_ra
        value: "2"
        state: present
        reload: true
      notify: reboot server

    - name: Set bridge-nf-call-iptables (just to be sure)
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: "1"
        state: present
        reload: true
      when: ansible_os_family == "RedHat"
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.bridge.bridge-nf-call-ip6tables
      notify: reboot server

  handlers:
    - name: Reboot server
      become: true
      ansible.builtin.reboot:
      listen: reboot server
