apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apiTokenSecret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.apiTokenSecret.key }}: {{ required "Secret value not defined" .Values.apiTokenSecret.value | b64enc | quote }}
