apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apiKeySecret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.apiKeySecret.key }}: {{ required "Secret value not defined" .Values.apiKeySecret.value | b64enc | quote }}
