apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name}}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ required "Secret key not defined" .Values.secret.key }}: {{ required "Secret value not defined" .Values.secret.value | b64enc | quote }}