---
###############################################################
#                   Authelia configuration                    #
###############################################################

theme: dark

server:
  address: 'tcp://:9091'

log:
  level: debug

totp:
  issuer: '{{ env "ROOT_DOMAIN" }}'

identity_validation:
  reset_password:
    jwt_secret: '{{ env "JWT_SECRET" }}'

authentication_backend:
  file:
    path: /data/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: 'authelia.{{ env "ROOT_DOMAIN" }}'
      policy: bypass
    - domain: 'jellyfin.{{ env "ROOT_DOMAIN" }}'
      policy: bypass
    - domain: 'immich.{{ env "ROOT_DOMAIN" }} '
      policy: bypass
    - domain: 'paperless.{{ env "ROOT_DOMAIN" }}'
      policy: two_factor

session:
  secret: '{{ env "SESSION_SECRET" }}'

  cookies:
    - name: authelia_session
      domain: '{{ env "ROOT_DOMAIN" }}' # Should match whatever your root protected domain is
      authelia_url: 'https://authelia.{{ env "ROOT_DOMAIN" }}''
      expiration: '1 hour'  # 1 hour
      inactivity: '5 minutes'  # 5 minutes
      default_redirection_url: 'https://{{ env "ROOT_DOMAIN" }}'

regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'

storage:
  encryption_key: '{{ env "STORAGE_ENCRYPTION_KEY" }}'
  local:
    path: /data/db.sqlite3

notifier:
  disable_startup_check: false
  smtp:
    username: '{{ env "GMAIL_ADDRESS" }}'
    password: '{{ env "GMAIL_APP_PASSWORD" }}'
    host: smtp.gmail.com
    port: 587
    sender: '{{ env "GMAIL_ADDRESS" }}'
    identifier: localhost
    subject: "[Authelia] {subject}"
    startup_check_address: '{{ env "GMAIL_ADDRESS" }}'
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
...