version: 3.0

tasks:
  default:
    cmds:
      - task: apply
  
  apply:
    desc: Apply Terraform configuration
    cmds:
      - terraform init
      - terraform apply

  destroy:
    desc: Destroy Terraform configuration
    cmds:
      - terraform init
      - terraform destroy

  plan:
    desc: Plan Terraform configuration
    cmds:
      - terraform init
      - terraform plan