# webapp.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: webapp
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.210  # Must be in your MetalLB IP pool
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx