services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    expose:
      - 9090
    user: 1000:1000
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ../volumes/prometheus:/prometheus
    restart: unless-stopped
    networks:
      - prometheus

networks:
  prometheus:
