services:
  paperless-redis:
    image: docker.io/library/redis:7
    restart: unless-stopped
    # volumes:
    #   - paperless-redis-data:/data
    networks:
      - paperless

  paperless-db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - ../volumes/paperless-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    networks:
      - paperless

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - paperless-db
      - paperless-redis
    expose:
      - 8000
    # ports:
    #   - "8000:8000"
    volumes:
      - ../volumes/paperless:/usr/src/paperless/data
      - ../volumes/paperless-media:/usr/src/paperless/media
      - ../volumes/paperless-export:/usr/src/paperless/export
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_DBHOST: paperless-db
      PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'
      # PAPERLESS_ENABLE_HTTP_REMOTE_USER: true
      # PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: HTTP_REMOTE_USER
    networks:
      - homelab-public
      - ofelia
      - paperless

networks:
  paperless:
