services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1000:1000 # should be owner of volumes
    ports:
      - 4533:4533
    restart: unless-stopped
    env_file: .env
    volumes:
      - ../volumes/navidrome:/data
      - ../../shared/media/music:/music:ro
    networks:
      - homelab-public