---
extra_server_args: ""

k3s_kubectl_binary: k3s kubectl

group_name_master: server

kube_vip_arp: true
kube_vip_iface:
kube_vip_cloud_provider_tag_version: main
kube_vip_tag_version: v0.7.2

kube_vip_bgp: false
kube_vip_bgp_routerid: 127.0.0.1
kube_vip_bgp_as: "64513"
kube_vip_bgp_peeraddress: 192.168.30.1
kube_vip_bgp_peeras: "64512"

kube_vip_bgp_peers: []
kube_vip_bgp_peers_groups: ['k3s_master']

metal_lb_controller_tag_version: v0.14.3
metal_lb_speaker_tag_version: v0.14.3
metal_lb_type: native

retry_count: 20

systemd_dir: /etc/systemd/system
