---
- name: Wait for API server on VIP
  ansible.builtin.wait_for:
    host: "{{ k3s_vip }}"
    port: 6443
    timeout: 300
    state: started

- name: Install k3s (join existing server)
  vars:
    k3s_token: "{{ groups['server'] | map('extract', hostvars) | map(attribute='k3s_token') | first }}"
  ansible.builtin.command:
    cmd: >
      /tmp/get-k3s.sh server
      --disable traefik --disable servicelb --flannel-iface eth0
      --server https://{{ k3s_vip }}:6443
      --token {{ k3s_token }}
    creates: /usr/local/bin/k3s-uninstall.sh

- name: Start k3s on joined servers
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: true
    daemon_reload: true
  when: not is_first_server
