---
- name: Stop k3s
  ansible.builtin.service:
    name: k3s
    state: stopped
  failed_when: false

- name: Uninstall previous k3s
  ansible.builtin.command:
    cmd: /usr/local/bin/k3s-uninstall.sh
    removes: /usr/local/bin/k3s-uninstall.sh
