apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: hsts
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
