services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    env_file: .env
    environment:
      PUID: 1000
      PGID: 1000