services:
  brewapi:
    image: ghcr.io/vjrasane/brewapi
    ports:
      - 3003:3000
    expose:
      - 3000
    env_file: .env
    restart: unless-stopped
    volumes:
      - ../volumes/brewapi:/data
    networks:
      - homelab-public
      - prometheus