services:
  trilium:
    image: zadam/trilium
    restart: unless-stopped
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    expose:
      - 8080
      # ports:
      # - "8080:8080"
    volumes:
      - trilium-data:/home/node/trilium-data

volumes:
  trilium-data:
    driver: local
