---
- name: Download k3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/get-k3s.sh
    mode: "0755"

- name: Install k3s
  ansible.builtin.command:
    cmd: >
      /tmp/get-k3s.sh agent
      --token '{{ k3s_token }}'
      --server 'https://{{ k3s_vip }}:6443'
    creates: /usr/local/bin/k3s-agent-uninstall.sh

- name: Start k3s-agent
  ansible.builtin.systemd:
    name: k3s-agent
    state: started
    enabled: true
    daemon_reload: true
