---
- name: Check if k3s is installed
  ansible.builtin.stat:
    path: /usr/local/bin/k3s-agent-uninstall.sh
  register: k3s_installed

- name: Uninstall previous k3s
  ansible.builtin.include_tasks: uninstall_k3s_agent.yml
  when:
    - k3s_installed.stat.exists
    - reinstall | default(false) | bool

- name: Install k3s agent
  ansible.builtin.include_tasks: install_k3s_agent.yml
  when:
    - not k3s_installed.stat.exists
    - reinstall | default(false) | bool
