services:
  linkding:
    container_name: linkding
    image: sissbruecker/linkding:latest
    expose:
      - 3003
    ports:
      - 9090:9090
    env_file: .env
    volumes:
      - ../volumes/linkding-:/etc/linkding/data
    restart: unless-stopped
    networks:
      - homelab-public
