---
- name: Reboot containers
  block:
    - name: Make sure container is started
      ansible.builtin.command: pct start {{ item }}
      loop: "{{ proxmox_lxc_container_vmids }}"
      register: lxc_start
      changed_when: true
      failed_when: >-
        lxc_start.rc != 0 and "already running" not in lxc_start.stderr
      listen: reboot containers
    - name: Reboot container
      ansible.builtin.command: pct reboot {{ item }}
      loop: "{{ proxmox_lxc_container_vmids }}"
      changed_when: true
      listen: reboot containers
    - name: Wait for SSH to be available
      ansible.builtin.wait_for:
        timeout: 15
        port: 22
        host: '{{ item }}'
        search_regex: 'OpenSSH'
      loop: '{{ proxmox_lxc_container_hostnames }}'
      listen: reboot containers
