services:
  nginx-proxy-manager:
    # image: 'jc21/nginx-proxy-manager:2.9.14'
    build: 
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "nginx-proxy-manager-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - nginx-proxy-manager-data:/data
      - letsencrypt-data:/etc/letsencrypt
    depends_on:
      - nginx-proxy-manager-db

  nginx-proxy-manager-db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - nginx-proxy-manager-db-data:/var/lib/mysql

volumes:
  nginx-proxy-manager-data:
    driver: local
  letsencrypt-data:
    driver: local  
  nginx-proxy-manager-db-data:
    driver: local
