services:
  linkwarden-db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - linwarden-db-data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres 
      POSTGRES_USER: postgres 
      POSTGRES_DB: linkwarden 

  linkwarden:
    env_file: .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@linkwarden-db:5432/linkwarden
      NEXT_PUBLIC_DISABLE_REGISTRATION: true
      # NEXTAUTH_SECRET
    restart: unless-stopped
    # build: . # uncomment this line to build from source
    image: ghcr.io/linkwarden/linkwarden:latest # comment this line to build from source
    expose: 
      - 3000
    # ports:
    #   - 3000:3000
    volumes:
      - linkwarden-data:/data/data
    depends_on:
      - linkwarden-db

volumes:
  linkwarden-data:
    driver: local
  linwarden-db-data:
    driver: local