---
server_hostname: "{{ groups['server'] | map('extract', hostvars) | map(attribute='ansible_host') | first }}"
server_token: "{{ groups['server'] | map('extract', hostvars) | map(attribute='token') | first }}"