apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: cert-manager
    namespace: cloudflare
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    version: v1.17.2
    valuesInline:
      installCRDs: true
