---
- name: Install k3s on servers
  hosts: server
  vars_files:
    - ../terraform/terraform_vars.yml
  tasks:
    - name: Download k3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/get-k3s.sh
        mode: '0755'
    - name: Install k3s
      ansible.builtin.command:
        cmd: /tmp/get-k3s.sh server --disable traefik --cluster-init
        creates: /etc/rancher/k3s/k3s.yaml
    - name: Copy config file to user home directory
      ansible.builtin.copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ ansible_user_dir }}/kube.conf"
        remote_src: true
        owner: "{{ ansible_user_id }}"
        follow: true
        mode: u=rw,g=,o=
