services:
  grimoire-pocketbase:
    image: spectado/pocketbase:0.22.10
    container_name: grimoire-pocketbase
    restart: unless-stopped
    volumes:
      - grimoire-data:/pb_data
      - grimoire-migrations:/pb_migrations/
    expose:
      - 80
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:80/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  grimoire:
    image: goniszewski/grimoire:latest
    container_name: grimoire
    restart: unless-stopped
    # env_file: .env
    volumes:
      - grimoire-migrations:/app/pb_migrations/
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5173/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      PUBLIC_POCKETBASE_URL: http://grimoire-pocketbase:80
      PUBLIC_SIGNUP_DISABLED: 'true'
      PUBLIC_ORIGIN: http://localhost:5173
      ROOT_ADMIN_EMAIL: admin@grimoire.localhost
      ROOT_ADMIN_PASSWORD: changeme
      PORT: 5173
    expose:
      - 5173
    depends_on:
      - grimoire-pocketbase

volumes:
  grimoire-data:
  grimoire-migrations: