---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

# - Admin:
    # - Portainer:
    #     icon: portainer.svg
    #     href: https://{{HOMEPAGE_VAR_HOSTNAME}}:9443
    #     description: Container management
    #     widget:
    #         type: portainer
    #         url: https://{{HOMEPAGE_VAR_HOSTNAME}}:9443
    #         env: 2
    #         key: {{HOMEPAGE_VAR_PORTAINER_TOKEN}}

- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: http://{{HOMEPAGE_VAR_HOSTNAME}}:8096
        description: Media streaming
        widget:
            type: jellyfin
            url: http://{{HOMEPAGE_VAR_HOSTNAME}}:8096
            key: {{HOMEPAGE_VAR_JELLYFIN_APIKEY}}
            enableBlocks: true 
            enableNowPlaying: true
            expandOneStreamToTwoRows: false # optional, defaults to true
